CREATE TABLE IF NOT EXISTS tasks (
    id BIGSERIAL PRIMARY KEY,
    title VARCHAR(100) NOT NULL CHECK (LENGTH(title) >= 1 AND LENGTH(title) <= 100),
    description VARCHAR(500) NOT NULL CHECK (LENGTH(description) <= 500),
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);